<?php

/**
 * Implementation of hook_menu().
 */
function os_menu() {
  $items['current-user'] = array(
    'title' => 'Current user information',
    'page callback' => '_current_user_page',
    'access callback' => TRUE,
    'type' => MENU_NORMAL_ITEM,
  );
  return $items;
}

/**
 * Callback function for the URL 'current-user'.
 */
function _current_user_page() {
  global $user;

  $fields = [];
  $fields['Login'] = $user->name;

  return theme('os', compact('fields'));
}

/**
 * Implementation of hook_theme().
 */
function os_theme() {
  $module_path = drupal_get_path('module', 'os');

  return array(
    'os' => array(
      'template' => 'os',
      'arguments' => 'fields',
      'path' => $module_path . '/templates',
    ),
  );
}